// Generates src/version.ts from package.json so SDK_VERSION is single-sourced
// and can never drift from the published npm version. Runs in `build` and
// `build:test`; the generated file is committed so a fresh clone typechecks
// without a pre-step. CI additionally asserts dist/version.js === package.json.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));
const out = join(here, "..", "src", "version.ts");

const body = `// GENERATED by scripts/genversion.mjs — do not edit by hand.
// Source of truth is the "version" field in package.json.
export const SDK_VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(out, body);
console.log(`genversion: wrote src/version.ts (SDK_VERSION = ${pkg.version})`);
