// Generates src/version.ts from package.json so SDK_VERSION is single-sourced
// and can never drift from the published npm version. Runs in `build` and
// `build:test`; the generated file is committed so a fresh clone typechecks
// without a pre-step. CI additionally asserts dist/version.js === package.json.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));
const out = join(here, "..", "src", "version.ts");

// The trailing `x-release-please-version` marker is LOAD-BEARING and must be emitted here,
// not only committed once. release-please updates this file through the generic updater,
// which finds the line by that annotation — and this script overwrites the whole file on
// every build. Writing the marker by hand and not here would work exactly until the next
// build stripped it, after which release-please would keep "updating" a file it could no
// longer find a version in, silently, and version.ts would drift again. Same marker the
// Python SDK carries on `__version__`.
const body = `// GENERATED by scripts/genversion.mjs — do not edit by hand.
// Source of truth is the "version" field in package.json.
export const SDK_VERSION = ${JSON.stringify(pkg.version)}; // x-release-please-version
`;

writeFileSync(out, body);
// Log to stderr so it never contaminates machine-readable stdout (e.g. the
// `npm pack --json` output the release/CI leak-check parses; prepack runs this).
console.error(`genversion: wrote src/version.ts (SDK_VERSION = ${pkg.version})`);
