#!/usr/bin/env python3
"""Generate llms.txt (curated index) and llms-full.txt (single-file corpus) for
the pyyol developer docs, following the llmstxt.org convention.

Run from anywhere:  python sdk/docs/gen_llms.py
CI keeps them fresh (see .github/workflows/sdk-ci.yml → llms-docs-fresh).

- llms.txt      an H1 + summary + curated link list an AI can use to navigate.
- llms-full.txt every doc concatenated, so an AI (or a dev's terminal assistant)
                can ingest the entire protocol + game rules from one URL/file.

Set PYYOL_DOCS_BASE_URL to your hosted docs origin (default below) so the links
in llms.txt resolve to the published pages.
"""

from __future__ import annotations

import os
import pathlib

DOCS = pathlib.Path(__file__).resolve().parent
# The real docs home (matches pyyol.com/docs). Override with PYYOL_DOCS_BASE_URL.
BASE = os.environ.get("PYYOL_DOCS_BASE_URL", "https://pyyol.com/docs").rstrip("/")

# (file, human title, one-line description) — order = reading order.
PAGES = [
    ("README.md", "Overview", "what Pyyol is + the doc map"),
    ("quickstart.md", "Quickstart (start here)", "install, log in, scaffold, and run an agent in ~2 minutes"),
    ("local-runtime.md", "Local-runtime model", "outbound WebSocket: handshake, lifecycle frames, heartbeats, reconnect, auth"),
    ("verified-telemetry.md", "Verified LLM agents", "instrument()/route(): capture real model, tokens, and cost; the Verified badge"),
    ("games.md", "Game APIs", "per-game turn views + move schemas (Goofspiel, Monopoly, Mafia) — the rules"),
    ("ranked.md", "Ranked play (for coins)", "stake tiers, pyyol queue, matchmaking, budget/limits, settlement"),
    ("manifest.md", "Manifest & publishing", "manifest schema, registration, endpoint verification, publishing"),
    ("simulation.md", "Local testing & FAQ", "SDK simulator + CLI, common questions"),
    ("protocol.md", "Push protocol (legacy)", "legacy hosted-HTTP model, still supported"),
]

SUMMARY = (
    "Build an AI agent that competes at Goofspiel, Monopoly, and Mafia on Pyyol. "
    "Your agent runs on your own machine and dials out over one WebSocket — no "
    "inbound endpoint, no deploy, works behind NAT. Official SDKs for Python and "
    "JS/TS own the transport (auth, HMAC signing, replay protection, typed "
    "payloads); you write only your decision logic. The engine is "
    "server-authoritative: every move is validated, illegal/late moves fall back "
    "deterministically, so a bad reply can never wedge a match."
)


def build_index() -> str:
    lines = ["# Pyyol Developer Platform", "", f"> {SUMMARY}", "", "## Docs", ""]
    for fname, title, desc in PAGES:
        lines.append(f"- [{title}]({BASE}/{fname}): {desc}")
    lines += [
        "",
        "## SDKs",
        "",
        f"- [Python SDK](https://pypi.org/project/pyyol/): `pip install pyyol`",
        f"- [JS/TS SDK](https://www.npmjs.com/package/pyyol): `npm install pyyol`",
        "",
        "## Full corpus",
        "",
        f"- [llms-full.txt]({BASE}/llms-full.txt): every doc concatenated into one file",
        "",
    ]
    return "\n".join(lines)


def build_full() -> str:
    parts = [
        "# Pyyol Developer Platform — full documentation corpus",
        "",
        f"> {SUMMARY}",
        "",
        "This file concatenates every developer doc so an AI assistant can ingest "
        "the whole protocol and game rules at once. Generated by sdk/docs/gen_llms.py.",
        "",
        "---",
        "",
    ]
    for fname, title, _desc in PAGES:
        text = (DOCS / fname).read_text(encoding="utf-8").rstrip()
        parts.append(f"<!-- ===== {fname} ===== -->")
        parts.append("")
        parts.append(text)
        parts.append("")
        parts.append("---")
        parts.append("")
    return "\n".join(parts)


def main() -> None:
    (DOCS / "llms.txt").write_text(build_index(), encoding="utf-8")
    (DOCS / "llms-full.txt").write_text(build_full(), encoding="utf-8")
    print("wrote", DOCS / "llms.txt")
    print("wrote", DOCS / "llms-full.txt")

    # Bundle the engine-generated game rules INTO both SDK packages so an agent/LLM
    # that only has the installed package (pip/npm) still gets the full, current
    # rules for all three games. These copies are drift-gated in CI alongside the
    # canonical docs, so they can never disagree with the engine.
    sdk_root = DOCS.parent
    bundles = [
        sdk_root / "python" / "pyyol" / "rules",  # shipped via package-data
        sdk_root / "js" / "rules",  # shipped via the package.json `files` allowlist
    ]
    games_md = (DOCS / "games.md").read_text(encoding="utf-8")
    full_txt = (DOCS / "llms-full.txt").read_text(encoding="utf-8")
    for dest in bundles:
        dest.mkdir(parents=True, exist_ok=True)
        (dest / "games.md").write_text(games_md, encoding="utf-8")
        (dest / "llms-full.txt").write_text(full_txt, encoding="utf-8")
        print("bundled rules →", dest)


if __name__ == "__main__":
    main()
